import React, { FormEvent, useEffect, useState } from 'react';
import Head from 'next/head';
import { Button, Paper, TextField } from '@mui/material';
import { useRouter } from 'next/router';

import useLogin from '../hooks/api/useLogin';

const style = {
  flexBox: { display: 'flex', height: '100vh', justifyContent: 'center', alignItems: 'center' },
  paper: { height: '60%', width: '40%' }
};

const Login = () => {

  const router = useRouter()

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const postLogin = useLogin(username,password)

  const submitLogin= async (e:FormEvent<HTMLFormElement>)=>{
    e.preventDefault();
    await postLogin();
  }

  return (
    <div>
      <Head>
        <title>Red-Binder | Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div style={style.flexBox}>
        <Paper style={style.paper}>
          <div style={{minHeight: '60%', minWidth: '40%'}}>
            <form onSubmit={(e)=>submitLogin(e)}>
            <TextField id='outlined-basic' type={'text'} label='Outlined' variant='outlined' fullWidth value={username} onChange={(e)=>setUsername(e.target.value)}/>
            <TextField id='outlined-basic' type={'password'} label='Outlined' variant='outlined' fullWidth value={password} onChange={(e)=>setPassword(e.target.value)}/>

            <Button variant='outlined' type={'submit'} fullWidth>Login</Button>
            </form>
            <Button variant='outlined' fullWidth onClick={()=>router.push('/signup')}>SignUp</Button>
          </div>
        </Paper>
      </div>
    </div>
  );
};

export default Login;
