import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button, Paper, TextField } from '@mui/material';
import { useRouter } from 'next/router';


const style = {
  flexBox: { display: 'flex', height: '100vh', justifyContent: 'center', alignItems: 'center' },
  paper: { height: '60%', width: '40%' }
};

const Signup = () => {

  const router = useRouter()


  return (
    <div className={styles.container}>
      <Head>
        <title>Red-Binder | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={style.flexBox}>
        <Paper style={style.paper}>
          <div style={{minHeight: '60%', minWidth: '40%'}}>
            <TextField id='outlined-basic' label='username' variant='outlined' fullWidth />
            <TextField id='outlined-basic' label='password' variant='outlined' fullWidth />
            <TextField id='outlined-basic' label='email' variant='outlined' fullWidth />
            <TextField id='outlined-basic' label='confirm password' variant='outlined' fullWidth />

            <Button variant='outlined' fullWidth onClick={()=>router.push('/signup')}>Submit</Button>
            <Button variant='outlined' fullWidth>Login</Button>
          </div>
        </Paper>
      </div>


    </div>
  );
};

export default Signup;
