export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const UPDATE_BINDERS = 'UPDATE_BINDERS';
export const UPDATE_SELECTED_BINDER_INDEX = 'UPDATE_SELECTED_BINDER_INDEX';